/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as AuthImport } from './routes/auth'
import { Route as AdminImport } from './routes/admin'
import { Route as ClientImport } from './routes/_client'
import { Route as AdminIndexImport } from './routes/admin/index'
import { Route as ClientIndexImport } from './routes/_client/index'
import { Route as AuthUpdatePasswordImport } from './routes/auth/update-password'
import { Route as AuthSignupImport } from './routes/auth/signup'
import { Route as AuthLoginImport } from './routes/auth/login'
import { Route as AuthForgotPasswordImport } from './routes/auth/forgot-password'
import { Route as AdminUsersImport } from './routes/admin/users'
import { Route as AdminTestimonialImport } from './routes/admin/testimonial'
import { Route as AdminServicesImport } from './routes/admin/services'
import { Route as AdminGalleryImport } from './routes/admin/gallery'
import { Route as ClientTeamImport } from './routes/_client/team'
import { Route as ClientServicesImport } from './routes/_client/services'
import { Route as ClientGalleryImport } from './routes/_client/gallery'
import { Route as ClientContactImport } from './routes/_client/contact'
import { Route as ClientAboutImport } from './routes/_client/about'
import { Route as AdminLocationsIndexImport } from './routes/admin/locations/index'
import { Route as AdminCategoriesIndexImport } from './routes/admin/categories/index'
import { Route as AdminAppointmentsIndexImport } from './routes/admin/appointments/index'
import { Route as AdminLocationsIdImport } from './routes/admin/locations/$id'
import { Route as AdminCategoriesIdImport } from './routes/admin/categories/$id'
import { Route as AdminAppointmentsIdImport } from './routes/admin/appointments/$id'
import { Route as ClientProfileUserInfoImport } from './routes/_client/profile/user-info'
import { Route as ClientProfileUserAppointmentsImport } from './routes/_client/profile/user-appointments'
import { Route as ClientProfileMyBookingsIndexImport } from './routes/_client/profile/my-bookings/index'
import { Route as ClientProfileBookingIndexImport } from './routes/_client/profile/booking/index'
import { Route as AdminLocationsIdStaffsIndexImport } from './routes/admin/locations/$id/staffs/index'
import { Route as AdminLocationsIdServicesIndexImport } from './routes/admin/locations/$id/services/index'
import { Route as ClientProfileBookingConfirmationIndexImport } from './routes/_client/profile/booking/confirmation/index'
import { Route as AdminLocationsIdServicesSearchImport } from './routes/admin/locations/$id/services/search'
import { Route as AdminLocationsIdStaffsStaffidSchedulesImport } from './routes/admin/locations/$id/staffs/$staffid/schedules'
import { Route as AdminLocationsIdStaffsStaffidReviewsImport } from './routes/admin/locations/$id/staffs/$staffid/reviews'

// Create/Update Routes

const AuthRoute = AuthImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRoute,
} as any)

const AdminRoute = AdminImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRoute,
} as any)

const ClientRoute = ClientImport.update({
  id: '/_client',
  getParentRoute: () => rootRoute,
} as any)

const AdminIndexRoute = AdminIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)

const ClientIndexRoute = ClientIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ClientRoute,
} as any)

const AuthUpdatePasswordRoute = AuthUpdatePasswordImport.update({
  id: '/update-password',
  path: '/update-password',
  getParentRoute: () => AuthRoute,
} as any)

const AuthSignupRoute = AuthSignupImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => AuthRoute,
} as any)

const AuthLoginRoute = AuthLoginImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRoute,
} as any)

const AuthForgotPasswordRoute = AuthForgotPasswordImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => AuthRoute,
} as any)

const AdminUsersRoute = AdminUsersImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)

const AdminTestimonialRoute = AdminTestimonialImport.update({
  id: '/testimonial',
  path: '/testimonial',
  getParentRoute: () => AdminRoute,
} as any)

const AdminServicesRoute = AdminServicesImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => AdminRoute,
} as any)

const AdminGalleryRoute = AdminGalleryImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => AdminRoute,
} as any)

const ClientTeamRoute = ClientTeamImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => ClientRoute,
} as any)

const ClientServicesRoute = ClientServicesImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => ClientRoute,
} as any)

const ClientGalleryRoute = ClientGalleryImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => ClientRoute,
} as any)

const ClientContactRoute = ClientContactImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => ClientRoute,
} as any)

const ClientAboutRoute = ClientAboutImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => ClientRoute,
} as any)

const AdminLocationsIndexRoute = AdminLocationsIndexImport.update({
  id: '/locations/',
  path: '/locations/',
  getParentRoute: () => AdminRoute,
} as any)

const AdminCategoriesIndexRoute = AdminCategoriesIndexImport.update({
  id: '/categories/',
  path: '/categories/',
  getParentRoute: () => AdminRoute,
} as any)

const AdminAppointmentsIndexRoute = AdminAppointmentsIndexImport.update({
  id: '/appointments/',
  path: '/appointments/',
  getParentRoute: () => AdminRoute,
} as any)

const AdminLocationsIdRoute = AdminLocationsIdImport.update({
  id: '/locations/$id',
  path: '/locations/$id',
  getParentRoute: () => AdminRoute,
} as any)

const AdminCategoriesIdRoute = AdminCategoriesIdImport.update({
  id: '/categories/$id',
  path: '/categories/$id',
  getParentRoute: () => AdminRoute,
} as any)

const AdminAppointmentsIdRoute = AdminAppointmentsIdImport.update({
  id: '/appointments/$id',
  path: '/appointments/$id',
  getParentRoute: () => AdminRoute,
} as any)

const ClientProfileUserInfoRoute = ClientProfileUserInfoImport.update({
  id: '/profile/user-info',
  path: '/profile/user-info',
  getParentRoute: () => ClientRoute,
} as any)

const ClientProfileUserAppointmentsRoute =
  ClientProfileUserAppointmentsImport.update({
    id: '/profile/user-appointments',
    path: '/profile/user-appointments',
    getParentRoute: () => ClientRoute,
  } as any)

const ClientProfileMyBookingsIndexRoute =
  ClientProfileMyBookingsIndexImport.update({
    id: '/profile/my-bookings/',
    path: '/profile/my-bookings/',
    getParentRoute: () => ClientRoute,
  } as any)

const ClientProfileBookingIndexRoute = ClientProfileBookingIndexImport.update({
  id: '/profile/booking/',
  path: '/profile/booking/',
  getParentRoute: () => ClientRoute,
} as any)

const AdminLocationsIdStaffsIndexRoute =
  AdminLocationsIdStaffsIndexImport.update({
    id: '/staffs/',
    path: '/staffs/',
    getParentRoute: () => AdminLocationsIdRoute,
  } as any)

const AdminLocationsIdServicesIndexRoute =
  AdminLocationsIdServicesIndexImport.update({
    id: '/services/',
    path: '/services/',
    getParentRoute: () => AdminLocationsIdRoute,
  } as any)

const ClientProfileBookingConfirmationIndexRoute =
  ClientProfileBookingConfirmationIndexImport.update({
    id: '/profile/booking/confirmation/',
    path: '/profile/booking/confirmation/',
    getParentRoute: () => ClientRoute,
  } as any)

const AdminLocationsIdServicesSearchRoute =
  AdminLocationsIdServicesSearchImport.update({
    id: '/services/search',
    path: '/services/search',
    getParentRoute: () => AdminLocationsIdRoute,
  } as any)

const AdminLocationsIdStaffsStaffidSchedulesRoute =
  AdminLocationsIdStaffsStaffidSchedulesImport.update({
    id: '/staffs/$staffid/schedules',
    path: '/staffs/$staffid/schedules',
    getParentRoute: () => AdminLocationsIdRoute,
  } as any)

const AdminLocationsIdStaffsStaffidReviewsRoute =
  AdminLocationsIdStaffsStaffidReviewsImport.update({
    id: '/staffs/$staffid/reviews',
    path: '/staffs/$staffid/reviews',
    getParentRoute: () => AdminLocationsIdRoute,
  } as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_client': {
      id: '/_client'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof ClientImport
      parentRoute: typeof rootRoute
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminImport
      parentRoute: typeof rootRoute
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthImport
      parentRoute: typeof rootRoute
    }
    '/_client/about': {
      id: '/_client/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof ClientAboutImport
      parentRoute: typeof ClientImport
    }
    '/_client/contact': {
      id: '/_client/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ClientContactImport
      parentRoute: typeof ClientImport
    }
    '/_client/gallery': {
      id: '/_client/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof ClientGalleryImport
      parentRoute: typeof ClientImport
    }
    '/_client/services': {
      id: '/_client/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ClientServicesImport
      parentRoute: typeof ClientImport
    }
    '/_client/team': {
      id: '/_client/team'
      path: '/team'
      fullPath: '/team'
      preLoaderRoute: typeof ClientTeamImport
      parentRoute: typeof ClientImport
    }
    '/admin/gallery': {
      id: '/admin/gallery'
      path: '/gallery'
      fullPath: '/admin/gallery'
      preLoaderRoute: typeof AdminGalleryImport
      parentRoute: typeof AdminImport
    }
    '/admin/services': {
      id: '/admin/services'
      path: '/services'
      fullPath: '/admin/services'
      preLoaderRoute: typeof AdminServicesImport
      parentRoute: typeof AdminImport
    }
    '/admin/testimonial': {
      id: '/admin/testimonial'
      path: '/testimonial'
      fullPath: '/admin/testimonial'
      preLoaderRoute: typeof AdminTestimonialImport
      parentRoute: typeof AdminImport
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersImport
      parentRoute: typeof AdminImport
    }
    '/auth/forgot-password': {
      id: '/auth/forgot-password'
      path: '/forgot-password'
      fullPath: '/auth/forgot-password'
      preLoaderRoute: typeof AuthForgotPasswordImport
      parentRoute: typeof AuthImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginImport
      parentRoute: typeof AuthImport
    }
    '/auth/signup': {
      id: '/auth/signup'
      path: '/signup'
      fullPath: '/auth/signup'
      preLoaderRoute: typeof AuthSignupImport
      parentRoute: typeof AuthImport
    }
    '/auth/update-password': {
      id: '/auth/update-password'
      path: '/update-password'
      fullPath: '/auth/update-password'
      preLoaderRoute: typeof AuthUpdatePasswordImport
      parentRoute: typeof AuthImport
    }
    '/_client/': {
      id: '/_client/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof ClientIndexImport
      parentRoute: typeof ClientImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexImport
      parentRoute: typeof AdminImport
    }
    '/_client/profile/user-appointments': {
      id: '/_client/profile/user-appointments'
      path: '/profile/user-appointments'
      fullPath: '/profile/user-appointments'
      preLoaderRoute: typeof ClientProfileUserAppointmentsImport
      parentRoute: typeof ClientImport
    }
    '/_client/profile/user-info': {
      id: '/_client/profile/user-info'
      path: '/profile/user-info'
      fullPath: '/profile/user-info'
      preLoaderRoute: typeof ClientProfileUserInfoImport
      parentRoute: typeof ClientImport
    }
    '/admin/appointments/$id': {
      id: '/admin/appointments/$id'
      path: '/appointments/$id'
      fullPath: '/admin/appointments/$id'
      preLoaderRoute: typeof AdminAppointmentsIdImport
      parentRoute: typeof AdminImport
    }
    '/admin/categories/$id': {
      id: '/admin/categories/$id'
      path: '/categories/$id'
      fullPath: '/admin/categories/$id'
      preLoaderRoute: typeof AdminCategoriesIdImport
      parentRoute: typeof AdminImport
    }
    '/admin/locations/$id': {
      id: '/admin/locations/$id'
      path: '/locations/$id'
      fullPath: '/admin/locations/$id'
      preLoaderRoute: typeof AdminLocationsIdImport
      parentRoute: typeof AdminImport
    }
    '/admin/appointments/': {
      id: '/admin/appointments/'
      path: '/appointments'
      fullPath: '/admin/appointments'
      preLoaderRoute: typeof AdminAppointmentsIndexImport
      parentRoute: typeof AdminImport
    }
    '/admin/categories/': {
      id: '/admin/categories/'
      path: '/categories'
      fullPath: '/admin/categories'
      preLoaderRoute: typeof AdminCategoriesIndexImport
      parentRoute: typeof AdminImport
    }
    '/admin/locations/': {
      id: '/admin/locations/'
      path: '/locations'
      fullPath: '/admin/locations'
      preLoaderRoute: typeof AdminLocationsIndexImport
      parentRoute: typeof AdminImport
    }
    '/_client/profile/booking/': {
      id: '/_client/profile/booking/'
      path: '/profile/booking'
      fullPath: '/profile/booking'
      preLoaderRoute: typeof ClientProfileBookingIndexImport
      parentRoute: typeof ClientImport
    }
    '/_client/profile/my-bookings/': {
      id: '/_client/profile/my-bookings/'
      path: '/profile/my-bookings'
      fullPath: '/profile/my-bookings'
      preLoaderRoute: typeof ClientProfileMyBookingsIndexImport
      parentRoute: typeof ClientImport
    }
    '/admin/locations/$id/services/search': {
      id: '/admin/locations/$id/services/search'
      path: '/services/search'
      fullPath: '/admin/locations/$id/services/search'
      preLoaderRoute: typeof AdminLocationsIdServicesSearchImport
      parentRoute: typeof AdminLocationsIdImport
    }
    '/_client/profile/booking/confirmation/': {
      id: '/_client/profile/booking/confirmation/'
      path: '/profile/booking/confirmation'
      fullPath: '/profile/booking/confirmation'
      preLoaderRoute: typeof ClientProfileBookingConfirmationIndexImport
      parentRoute: typeof ClientImport
    }
    '/admin/locations/$id/services/': {
      id: '/admin/locations/$id/services/'
      path: '/services'
      fullPath: '/admin/locations/$id/services'
      preLoaderRoute: typeof AdminLocationsIdServicesIndexImport
      parentRoute: typeof AdminLocationsIdImport
    }
    '/admin/locations/$id/staffs/': {
      id: '/admin/locations/$id/staffs/'
      path: '/staffs'
      fullPath: '/admin/locations/$id/staffs'
      preLoaderRoute: typeof AdminLocationsIdStaffsIndexImport
      parentRoute: typeof AdminLocationsIdImport
    }
    '/admin/locations/$id/staffs/$staffid/reviews': {
      id: '/admin/locations/$id/staffs/$staffid/reviews'
      path: '/staffs/$staffid/reviews'
      fullPath: '/admin/locations/$id/staffs/$staffid/reviews'
      preLoaderRoute: typeof AdminLocationsIdStaffsStaffidReviewsImport
      parentRoute: typeof AdminLocationsIdImport
    }
    '/admin/locations/$id/staffs/$staffid/schedules': {
      id: '/admin/locations/$id/staffs/$staffid/schedules'
      path: '/staffs/$staffid/schedules'
      fullPath: '/admin/locations/$id/staffs/$staffid/schedules'
      preLoaderRoute: typeof AdminLocationsIdStaffsStaffidSchedulesImport
      parentRoute: typeof AdminLocationsIdImport
    }
  }
}

// Create and export the route tree

interface ClientRouteChildren {
  ClientAboutRoute: typeof ClientAboutRoute
  ClientContactRoute: typeof ClientContactRoute
  ClientGalleryRoute: typeof ClientGalleryRoute
  ClientServicesRoute: typeof ClientServicesRoute
  ClientTeamRoute: typeof ClientTeamRoute
  ClientIndexRoute: typeof ClientIndexRoute
  ClientProfileUserAppointmentsRoute: typeof ClientProfileUserAppointmentsRoute
  ClientProfileUserInfoRoute: typeof ClientProfileUserInfoRoute
  ClientProfileBookingIndexRoute: typeof ClientProfileBookingIndexRoute
  ClientProfileMyBookingsIndexRoute: typeof ClientProfileMyBookingsIndexRoute
  ClientProfileBookingConfirmationIndexRoute: typeof ClientProfileBookingConfirmationIndexRoute
}

const ClientRouteChildren: ClientRouteChildren = {
  ClientAboutRoute: ClientAboutRoute,
  ClientContactRoute: ClientContactRoute,
  ClientGalleryRoute: ClientGalleryRoute,
  ClientServicesRoute: ClientServicesRoute,
  ClientTeamRoute: ClientTeamRoute,
  ClientIndexRoute: ClientIndexRoute,
  ClientProfileUserAppointmentsRoute: ClientProfileUserAppointmentsRoute,
  ClientProfileUserInfoRoute: ClientProfileUserInfoRoute,
  ClientProfileBookingIndexRoute: ClientProfileBookingIndexRoute,
  ClientProfileMyBookingsIndexRoute: ClientProfileMyBookingsIndexRoute,
  ClientProfileBookingConfirmationIndexRoute:
    ClientProfileBookingConfirmationIndexRoute,
}

const ClientRouteWithChildren =
  ClientRoute._addFileChildren(ClientRouteChildren)

interface AdminLocationsIdRouteChildren {
  AdminLocationsIdServicesSearchRoute: typeof AdminLocationsIdServicesSearchRoute
  AdminLocationsIdServicesIndexRoute: typeof AdminLocationsIdServicesIndexRoute
  AdminLocationsIdStaffsIndexRoute: typeof AdminLocationsIdStaffsIndexRoute
  AdminLocationsIdStaffsStaffidReviewsRoute: typeof AdminLocationsIdStaffsStaffidReviewsRoute
  AdminLocationsIdStaffsStaffidSchedulesRoute: typeof AdminLocationsIdStaffsStaffidSchedulesRoute
}

const AdminLocationsIdRouteChildren: AdminLocationsIdRouteChildren = {
  AdminLocationsIdServicesSearchRoute: AdminLocationsIdServicesSearchRoute,
  AdminLocationsIdServicesIndexRoute: AdminLocationsIdServicesIndexRoute,
  AdminLocationsIdStaffsIndexRoute: AdminLocationsIdStaffsIndexRoute,
  AdminLocationsIdStaffsStaffidReviewsRoute:
    AdminLocationsIdStaffsStaffidReviewsRoute,
  AdminLocationsIdStaffsStaffidSchedulesRoute:
    AdminLocationsIdStaffsStaffidSchedulesRoute,
}

const AdminLocationsIdRouteWithChildren =
  AdminLocationsIdRoute._addFileChildren(AdminLocationsIdRouteChildren)

interface AdminRouteChildren {
  AdminGalleryRoute: typeof AdminGalleryRoute
  AdminServicesRoute: typeof AdminServicesRoute
  AdminTestimonialRoute: typeof AdminTestimonialRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminAppointmentsIdRoute: typeof AdminAppointmentsIdRoute
  AdminCategoriesIdRoute: typeof AdminCategoriesIdRoute
  AdminLocationsIdRoute: typeof AdminLocationsIdRouteWithChildren
  AdminAppointmentsIndexRoute: typeof AdminAppointmentsIndexRoute
  AdminCategoriesIndexRoute: typeof AdminCategoriesIndexRoute
  AdminLocationsIndexRoute: typeof AdminLocationsIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminGalleryRoute: AdminGalleryRoute,
  AdminServicesRoute: AdminServicesRoute,
  AdminTestimonialRoute: AdminTestimonialRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminAppointmentsIdRoute: AdminAppointmentsIdRoute,
  AdminCategoriesIdRoute: AdminCategoriesIdRoute,
  AdminLocationsIdRoute: AdminLocationsIdRouteWithChildren,
  AdminAppointmentsIndexRoute: AdminAppointmentsIndexRoute,
  AdminCategoriesIndexRoute: AdminCategoriesIndexRoute,
  AdminLocationsIndexRoute: AdminLocationsIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface AuthRouteChildren {
  AuthForgotPasswordRoute: typeof AuthForgotPasswordRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthSignupRoute: typeof AuthSignupRoute
  AuthUpdatePasswordRoute: typeof AuthUpdatePasswordRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthForgotPasswordRoute: AuthForgotPasswordRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthSignupRoute: AuthSignupRoute,
  AuthUpdatePasswordRoute: AuthUpdatePasswordRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

export interface FileRoutesByFullPath {
  '': typeof ClientRouteWithChildren
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRouteWithChildren
  '/about': typeof ClientAboutRoute
  '/contact': typeof ClientContactRoute
  '/gallery': typeof ClientGalleryRoute
  '/services': typeof ClientServicesRoute
  '/team': typeof ClientTeamRoute
  '/admin/gallery': typeof AdminGalleryRoute
  '/admin/services': typeof AdminServicesRoute
  '/admin/testimonial': typeof AdminTestimonialRoute
  '/admin/users': typeof AdminUsersRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/signup': typeof AuthSignupRoute
  '/auth/update-password': typeof AuthUpdatePasswordRoute
  '/': typeof ClientIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/profile/user-appointments': typeof ClientProfileUserAppointmentsRoute
  '/profile/user-info': typeof ClientProfileUserInfoRoute
  '/admin/appointments/$id': typeof AdminAppointmentsIdRoute
  '/admin/categories/$id': typeof AdminCategoriesIdRoute
  '/admin/locations/$id': typeof AdminLocationsIdRouteWithChildren
  '/admin/appointments': typeof AdminAppointmentsIndexRoute
  '/admin/categories': typeof AdminCategoriesIndexRoute
  '/admin/locations': typeof AdminLocationsIndexRoute
  '/profile/booking': typeof ClientProfileBookingIndexRoute
  '/profile/my-bookings': typeof ClientProfileMyBookingsIndexRoute
  '/admin/locations/$id/services/search': typeof AdminLocationsIdServicesSearchRoute
  '/profile/booking/confirmation': typeof ClientProfileBookingConfirmationIndexRoute
  '/admin/locations/$id/services': typeof AdminLocationsIdServicesIndexRoute
  '/admin/locations/$id/staffs': typeof AdminLocationsIdStaffsIndexRoute
  '/admin/locations/$id/staffs/$staffid/reviews': typeof AdminLocationsIdStaffsStaffidReviewsRoute
  '/admin/locations/$id/staffs/$staffid/schedules': typeof AdminLocationsIdStaffsStaffidSchedulesRoute
}

export interface FileRoutesByTo {
  '/auth': typeof AuthRouteWithChildren
  '/about': typeof ClientAboutRoute
  '/contact': typeof ClientContactRoute
  '/gallery': typeof ClientGalleryRoute
  '/services': typeof ClientServicesRoute
  '/team': typeof ClientTeamRoute
  '/admin/gallery': typeof AdminGalleryRoute
  '/admin/services': typeof AdminServicesRoute
  '/admin/testimonial': typeof AdminTestimonialRoute
  '/admin/users': typeof AdminUsersRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/signup': typeof AuthSignupRoute
  '/auth/update-password': typeof AuthUpdatePasswordRoute
  '/': typeof ClientIndexRoute
  '/admin': typeof AdminIndexRoute
  '/profile/user-appointments': typeof ClientProfileUserAppointmentsRoute
  '/profile/user-info': typeof ClientProfileUserInfoRoute
  '/admin/appointments/$id': typeof AdminAppointmentsIdRoute
  '/admin/categories/$id': typeof AdminCategoriesIdRoute
  '/admin/locations/$id': typeof AdminLocationsIdRouteWithChildren
  '/admin/appointments': typeof AdminAppointmentsIndexRoute
  '/admin/categories': typeof AdminCategoriesIndexRoute
  '/admin/locations': typeof AdminLocationsIndexRoute
  '/profile/booking': typeof ClientProfileBookingIndexRoute
  '/profile/my-bookings': typeof ClientProfileMyBookingsIndexRoute
  '/admin/locations/$id/services/search': typeof AdminLocationsIdServicesSearchRoute
  '/profile/booking/confirmation': typeof ClientProfileBookingConfirmationIndexRoute
  '/admin/locations/$id/services': typeof AdminLocationsIdServicesIndexRoute
  '/admin/locations/$id/staffs': typeof AdminLocationsIdStaffsIndexRoute
  '/admin/locations/$id/staffs/$staffid/reviews': typeof AdminLocationsIdStaffsStaffidReviewsRoute
  '/admin/locations/$id/staffs/$staffid/schedules': typeof AdminLocationsIdStaffsStaffidSchedulesRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/_client': typeof ClientRouteWithChildren
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRouteWithChildren
  '/_client/about': typeof ClientAboutRoute
  '/_client/contact': typeof ClientContactRoute
  '/_client/gallery': typeof ClientGalleryRoute
  '/_client/services': typeof ClientServicesRoute
  '/_client/team': typeof ClientTeamRoute
  '/admin/gallery': typeof AdminGalleryRoute
  '/admin/services': typeof AdminServicesRoute
  '/admin/testimonial': typeof AdminTestimonialRoute
  '/admin/users': typeof AdminUsersRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/signup': typeof AuthSignupRoute
  '/auth/update-password': typeof AuthUpdatePasswordRoute
  '/_client/': typeof ClientIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/_client/profile/user-appointments': typeof ClientProfileUserAppointmentsRoute
  '/_client/profile/user-info': typeof ClientProfileUserInfoRoute
  '/admin/appointments/$id': typeof AdminAppointmentsIdRoute
  '/admin/categories/$id': typeof AdminCategoriesIdRoute
  '/admin/locations/$id': typeof AdminLocationsIdRouteWithChildren
  '/admin/appointments/': typeof AdminAppointmentsIndexRoute
  '/admin/categories/': typeof AdminCategoriesIndexRoute
  '/admin/locations/': typeof AdminLocationsIndexRoute
  '/_client/profile/booking/': typeof ClientProfileBookingIndexRoute
  '/_client/profile/my-bookings/': typeof ClientProfileMyBookingsIndexRoute
  '/admin/locations/$id/services/search': typeof AdminLocationsIdServicesSearchRoute
  '/_client/profile/booking/confirmation/': typeof ClientProfileBookingConfirmationIndexRoute
  '/admin/locations/$id/services/': typeof AdminLocationsIdServicesIndexRoute
  '/admin/locations/$id/staffs/': typeof AdminLocationsIdStaffsIndexRoute
  '/admin/locations/$id/staffs/$staffid/reviews': typeof AdminLocationsIdStaffsStaffidReviewsRoute
  '/admin/locations/$id/staffs/$staffid/schedules': typeof AdminLocationsIdStaffsStaffidSchedulesRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | ''
    | '/admin'
    | '/auth'
    | '/about'
    | '/contact'
    | '/gallery'
    | '/services'
    | '/team'
    | '/admin/gallery'
    | '/admin/services'
    | '/admin/testimonial'
    | '/admin/users'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/signup'
    | '/auth/update-password'
    | '/'
    | '/admin/'
    | '/profile/user-appointments'
    | '/profile/user-info'
    | '/admin/appointments/$id'
    | '/admin/categories/$id'
    | '/admin/locations/$id'
    | '/admin/appointments'
    | '/admin/categories'
    | '/admin/locations'
    | '/profile/booking'
    | '/profile/my-bookings'
    | '/admin/locations/$id/services/search'
    | '/profile/booking/confirmation'
    | '/admin/locations/$id/services'
    | '/admin/locations/$id/staffs'
    | '/admin/locations/$id/staffs/$staffid/reviews'
    | '/admin/locations/$id/staffs/$staffid/schedules'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/auth'
    | '/about'
    | '/contact'
    | '/gallery'
    | '/services'
    | '/team'
    | '/admin/gallery'
    | '/admin/services'
    | '/admin/testimonial'
    | '/admin/users'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/signup'
    | '/auth/update-password'
    | '/'
    | '/admin'
    | '/profile/user-appointments'
    | '/profile/user-info'
    | '/admin/appointments/$id'
    | '/admin/categories/$id'
    | '/admin/locations/$id'
    | '/admin/appointments'
    | '/admin/categories'
    | '/admin/locations'
    | '/profile/booking'
    | '/profile/my-bookings'
    | '/admin/locations/$id/services/search'
    | '/profile/booking/confirmation'
    | '/admin/locations/$id/services'
    | '/admin/locations/$id/staffs'
    | '/admin/locations/$id/staffs/$staffid/reviews'
    | '/admin/locations/$id/staffs/$staffid/schedules'
  id:
    | '__root__'
    | '/_client'
    | '/admin'
    | '/auth'
    | '/_client/about'
    | '/_client/contact'
    | '/_client/gallery'
    | '/_client/services'
    | '/_client/team'
    | '/admin/gallery'
    | '/admin/services'
    | '/admin/testimonial'
    | '/admin/users'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/signup'
    | '/auth/update-password'
    | '/_client/'
    | '/admin/'
    | '/_client/profile/user-appointments'
    | '/_client/profile/user-info'
    | '/admin/appointments/$id'
    | '/admin/categories/$id'
    | '/admin/locations/$id'
    | '/admin/appointments/'
    | '/admin/categories/'
    | '/admin/locations/'
    | '/_client/profile/booking/'
    | '/_client/profile/my-bookings/'
    | '/admin/locations/$id/services/search'
    | '/_client/profile/booking/confirmation/'
    | '/admin/locations/$id/services/'
    | '/admin/locations/$id/staffs/'
    | '/admin/locations/$id/staffs/$staffid/reviews'
    | '/admin/locations/$id/staffs/$staffid/schedules'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  ClientRoute: typeof ClientRouteWithChildren
  AdminRoute: typeof AdminRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
}

const rootRouteChildren: RootRouteChildren = {
  ClientRoute: ClientRouteWithChildren,
  AdminRoute: AdminRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/_client",
        "/admin",
        "/auth"
      ]
    },
    "/_client": {
      "filePath": "_client.tsx",
      "children": [
        "/_client/about",
        "/_client/contact",
        "/_client/gallery",
        "/_client/services",
        "/_client/team",
        "/_client/",
        "/_client/profile/user-appointments",
        "/_client/profile/user-info",
        "/_client/profile/booking/",
        "/_client/profile/my-bookings/",
        "/_client/profile/booking/confirmation/"
      ]
    },
    "/admin": {
      "filePath": "admin.tsx",
      "children": [
        "/admin/gallery",
        "/admin/services",
        "/admin/testimonial",
        "/admin/users",
        "/admin/",
        "/admin/appointments/$id",
        "/admin/categories/$id",
        "/admin/locations/$id",
        "/admin/appointments/",
        "/admin/categories/",
        "/admin/locations/"
      ]
    },
    "/auth": {
      "filePath": "auth.tsx",
      "children": [
        "/auth/forgot-password",
        "/auth/login",
        "/auth/signup",
        "/auth/update-password"
      ]
    },
    "/_client/about": {
      "filePath": "_client/about.tsx",
      "parent": "/_client"
    },
    "/_client/contact": {
      "filePath": "_client/contact.tsx",
      "parent": "/_client"
    },
    "/_client/gallery": {
      "filePath": "_client/gallery.tsx",
      "parent": "/_client"
    },
    "/_client/services": {
      "filePath": "_client/services.tsx",
      "parent": "/_client"
    },
    "/_client/team": {
      "filePath": "_client/team.tsx",
      "parent": "/_client"
    },
    "/admin/gallery": {
      "filePath": "admin/gallery.tsx",
      "parent": "/admin"
    },
    "/admin/services": {
      "filePath": "admin/services.tsx",
      "parent": "/admin"
    },
    "/admin/testimonial": {
      "filePath": "admin/testimonial.tsx",
      "parent": "/admin"
    },
    "/admin/users": {
      "filePath": "admin/users.tsx",
      "parent": "/admin"
    },
    "/auth/forgot-password": {
      "filePath": "auth/forgot-password.tsx",
      "parent": "/auth"
    },
    "/auth/login": {
      "filePath": "auth/login.tsx",
      "parent": "/auth"
    },
    "/auth/signup": {
      "filePath": "auth/signup.tsx",
      "parent": "/auth"
    },
    "/auth/update-password": {
      "filePath": "auth/update-password.tsx",
      "parent": "/auth"
    },
    "/_client/": {
      "filePath": "_client/index.tsx",
      "parent": "/_client"
    },
    "/admin/": {
      "filePath": "admin/index.tsx",
      "parent": "/admin"
    },
    "/_client/profile/user-appointments": {
      "filePath": "_client/profile/user-appointments.tsx",
      "parent": "/_client"
    },
    "/_client/profile/user-info": {
      "filePath": "_client/profile/user-info.tsx",
      "parent": "/_client"
    },
    "/admin/appointments/$id": {
      "filePath": "admin/appointments/$id.tsx",
      "parent": "/admin"
    },
    "/admin/categories/$id": {
      "filePath": "admin/categories/$id.tsx",
      "parent": "/admin"
    },
    "/admin/locations/$id": {
      "filePath": "admin/locations/$id.tsx",
      "parent": "/admin",
      "children": [
        "/admin/locations/$id/services/search",
        "/admin/locations/$id/services/",
        "/admin/locations/$id/staffs/",
        "/admin/locations/$id/staffs/$staffid/reviews",
        "/admin/locations/$id/staffs/$staffid/schedules"
      ]
    },
    "/admin/appointments/": {
      "filePath": "admin/appointments/index.tsx",
      "parent": "/admin"
    },
    "/admin/categories/": {
      "filePath": "admin/categories/index.tsx",
      "parent": "/admin"
    },
    "/admin/locations/": {
      "filePath": "admin/locations/index.tsx",
      "parent": "/admin"
    },
    "/_client/profile/booking/": {
      "filePath": "_client/profile/booking/index.tsx",
      "parent": "/_client"
    },
    "/_client/profile/my-bookings/": {
      "filePath": "_client/profile/my-bookings/index.tsx",
      "parent": "/_client"
    },
    "/admin/locations/$id/services/search": {
      "filePath": "admin/locations/$id/services/search.tsx",
      "parent": "/admin/locations/$id"
    },
    "/_client/profile/booking/confirmation/": {
      "filePath": "_client/profile/booking/confirmation/index.tsx",
      "parent": "/_client"
    },
    "/admin/locations/$id/services/": {
      "filePath": "admin/locations/$id/services/index.tsx",
      "parent": "/admin/locations/$id"
    },
    "/admin/locations/$id/staffs/": {
      "filePath": "admin/locations/$id/staffs/index.tsx",
      "parent": "/admin/locations/$id"
    },
    "/admin/locations/$id/staffs/$staffid/reviews": {
      "filePath": "admin/locations/$id/staffs/$staffid/reviews.tsx",
      "parent": "/admin/locations/$id"
    },
    "/admin/locations/$id/staffs/$staffid/schedules": {
      "filePath": "admin/locations/$id/staffs/$staffid/schedules.tsx",
      "parent": "/admin/locations/$id"
    }
  }
}
ROUTE_MANIFEST_END */
